# services:
#   luxonis:
#     image: husarion/depthai:humble-2.8.1-20240127
#     volumes:
#       - /dev/bus/usb:/dev/bus/usb
#       - ./squashfs-root/usr/share/husarion-depthai/config/oak-1-low-bandwidth.yaml:/params.yaml
#     device_cgroup_rules:
#       - 'c 189:* rmw'
#     command: >
#       ros2 launch depthai_ros_driver camera.launch.py
#         params_file:=/params.yaml

# x-common-config:
#   &common-config
#   network_mode: host
#   ipc: host
#   restart: unless-stopped

# x-dds-envs:
#   &dds-envs
#   env_file: .env.dds

services:

  rviz:
    image: husarion/rviz2:humble-11.2.9-20240111
    network_mode: host
    ipc: host
    runtime: ${DOCKER_RUNTIME:-runc}
    volumes:
      - /tmp/.X11-unix:/tmp/.X11-unix:rw
      - ./default.rviz:/default.rviz
      - ./rviz.launch.py:/rviz.launch.py
    environment:
      - DISPLAY=${DISPLAY:?err}
      - LIBGL_ALWAYS_SOFTWARE=${LIBGL_ALWAYS_SOFTWARE:-1}
      - NVIDIA_VISIBLE_DEVICES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
      - NVIDIA_DRIVER_CAPABILITIES=all # if LIBGL_ALWAYS_SOFTWARE=1 this env var is ignored
    command: ros2 launch /rviz.launch.py

