name: husarion-depthai
adopt-info: husarion-depthai
license: Apache-2.0
summary: The husarion-depthai
description: |
  The husarion-depthai.

  It offers the following parameters,

  - ros-domain-id
  - ros-localhost-only
  - fastdds-default-profiles-file
  - transport

  which can be set as follows, e.g.,

    snap set husarion-depthai ros-domain-id=1

grade: stable
confinement: strict
base: core22

contact: https://github.com/husarion/depthai-snap/issues
issues: https://github.com/husarion/depthai-snap/issues
website: https://husarion.com/

architectures:
  - build-on: amd64
    build-for: amd64
  # - build-on: amd64
  #   build-for: arm64
  - build-on: arm64
    build-for: arm64

slots:
  shm-slot:
    interface: shared-memory
    write: ['*'] # paths are relative to /dev/shm
  c189-slot:
    interface: custom-device
    custom-device: c189
    files:
      write:
        - /run/udev/data/c189:*

plugs:
  shm-plug:
    interface: shared-memory
    shared-memory: shm-slot
    private: false

  c189-plug:
    interface: custom-device
    custom-device: c189

apps:

  daemon:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/ros_setup.sh]
    daemon: simple
    install-mode: disable
    plugs: [network, network-bind, shm-plug, raw-usb, c189-plug]
    slots: [shm-slot, c189-slot]
    extensions: [ros2-humble-ros-base]

  husarion-depthai:
    command: usr/bin/launcher.sh
    command-chain: [usr/bin/check_daemon_running.sh, usr/bin/ros_setup.sh]
    plugs: [network, network-bind, shm-plug, raw-usb, c189-plug]
    # plugs: [network, network-bind, shm-plug, raw-usb, system-observe, hardware-observe, network-control, network-observe, camera, browser-support]
    # block-devices, 
    slots: [shm-slot, c189-slot]
    extensions: [ros2-humble-ros-base]

  start:
    command: usr/bin/start_launcher.sh

  stop:
    command: usr/bin/stop_launcher.sh

parts:

  husarion-depthai:
    plugin: nil
    stage-packages:
      - ros-humble-depthai-ros
      - ros-humble-image-transport
      - ros-humble-image-transport-plugins
      # https://index.ros.org/p/ffmpeg_image_transport/github-ros-misc-utilities-ffmpeg_image_transport/#humble
      - ros-humble-ffmpeg-image-transport
      - ffmpeg
      - ros-humble-cv-bridge
      # needed to run ffmpeg without errors:
      - libpulse-dev
      - libblas3
      - libjpeg-turbo8-dev
    override-stage: |
      craftctl default
      version="$(apt-cache policy ros-humble-depthai-ros-driver | grep Candidate | awk '{print $2}')"
      craftctl set version="$version"
      craftctl set grade="stable"

  # ffmpeg:
  #   plugin: colcon
  #   source: https://github.com/ros-misc-utilities/ffmpeg_image_transport.git
  #   # source-branch: v2.9.0-humble
  #   build-packages:
  #     - python3-catkin-pkg-modules
  #     - python3-vcstool
  #   stage-packages:
  #     - ros-humble-image-transport
  #     - ros-humble-image-transport-plugins
  #     - ffmpeg
  #     - ros-humble-cv-bridge
  #     # needed to run ffmpeg without errors:
  #     - libpulse-dev
  #     - libblas3
  #     - libjpeg-turbo8-dev
  #   override-pull: |
  #     craftctl default
  #     cd $CRAFT_PART_SRC
  #     vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/ffmpeg_image_transport.repos


  # husarion-depthai:
  #   plugin: colcon
  #   source: https://github.com/luxonis/depthai-ros.git
  #   source-branch: v2.9.0-humble
  #   build-packages:
  #     - python3-catkin-pkg-modules
  #     - python3-vcstool
  #   override-pull: |
  #     craftctl default

  #     cd $CRAFT_PART_SRC

  #     git clone https://github.com/ros-misc-utilities/ffmpeg_image_transport.git
  #     vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/ffmpeg_image_transport/ffmpeg_image_transport.repos

  #     # Set the snap version from the git tag
  #     # The grade is set to 'stable' if the latest entry in the git history
  #     # is the tag itself, otherwise set to devel
  #     version="$(git describe --always --tags| sed -e 's/^v//;s/-/+git/;y/-/./')"
  #     [ -n "$(echo $version | grep "+git")" ] && grade=devel || grade=stable
  #     craftctl set version="$version"
  #     craftctl set grade="$grade"

    # build-packages: 
    #   - python3-vcstool
    #   - python3-pip
    #   - python3-colcon-common-extensions
    #   - python3-rosdep
    #   - python3-catkin-pkg
      
  # ffmpeg:
  #   plugin: colcon
  #   source: https://github.com/ros-misc-utilities/ffmpeg_image_transport.git
  #   build-packages: 
  #     - python3-vcstool
  #     - python3-pip
  #     - python3-colcon-common-extensions
  #     - python3-rosdep
  #   override-pull: |
  #     craftctl default

  #     vcs import $CRAFT_PART_SRC < $CRAFT_PART_SRC/ffmpeg_image_transport.repos
  yq:
    plugin: nil
    override-build: |
      craftctl default

      YQ_VERSION="v4.35.1"
      TARGETARCH=$CRAFT_ARCH_BUILD_FOR
      curl -L "https://github.com/mikefarah/yq/releases/download/${YQ_VERSION}/yq_linux_${TARGETARCH}" -o $CRAFT_PART_BUILD/yq
    override-prime: |
      craftctl default
    
      cp $CRAFT_PART_BUILD/yq $CRAFT_PRIME/usr/bin/yq
      chmod +x $CRAFT_PRIME/usr/bin/yq
    build-packages:
      - curl

  # copy local scripts to the snap usr/bin
  local-files-ros:
    plugin: dump
    source: snap/local/ros_common/
    organize:
      '*.sh': usr/bin/
      '*.xml': usr/share/husarion-depthai/config/

  local-files:
    plugin: dump
    source: snap/local/
    organize:
      '*.sh': usr/bin/
      '*.py': usr/bin/
      '*.yaml': usr/share/husarion-depthai/config/
      # '*.xml': usr/share/husarion-depthai/config/
      # '*.json': usr/share/husarion-depthai/config/
